"""Expose the version declared only in project metadata, resolved on first use."""

from __future__ import annotations

import importlib
from functools import cache
from pathlib import Path
from typing import Final

DISTRIBUTION_NAME: Final = "eml-attachment-remover"
PROJECT_CONFIG: Final = Path(__file__).resolve().parents[2] / "pyproject.toml"


def distribution_version(name: str) -> str:
    """Read one installed distribution's version from packaging metadata.

    The metadata machinery is imported here, not at module import, because it costs
    more than the rest of this program's startup and most runs never print a version.

    Returns:
        The version recorded for the installed distribution.

    """
    metadata = importlib.import_module("importlib.metadata")
    return str(metadata.version(name))


def _project_version() -> str:
    """Read the version from the source-tree project metadata.

    Returns:
        The static project version declared in ``pyproject.toml``.

    """
    tomllib = importlib.import_module("tomllib")
    with PROJECT_CONFIG.open("rb") as project_file:
        metadata = tomllib.load(project_file)
    return str(metadata["project"]["version"])


def _resolved_version() -> str:
    """Read installed metadata, falling back to source-tree metadata.

    Returns:
        The version generated by packaging metadata or declared in ``pyproject.toml``.

    """
    metadata = importlib.import_module("importlib.metadata")
    try:
        return distribution_version(DISTRIBUTION_NAME)
    except metadata.PackageNotFoundError:
        return _project_version()


@cache
def program_version() -> str:
    """Return the program version, resolved once and only when first asked for.

    Returns:
        The same version the eager module attribute used to hold.

    """
    return _resolved_version()


def __getattr__(name: str) -> str:
    """Resolve ``PROGRAM_VERSION`` on first access, keeping the attribute public.

    Returns:
        The program version.

    Raises:
        AttributeError: If any other missing attribute is requested.

    """
    if name == "PROGRAM_VERSION":
        return program_version()
    message = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(message)
