"""Expose the version declared only in project metadata."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as distribution_version
from pathlib import Path
from tomllib import load
from typing import Final

DISTRIBUTION_NAME: Final = "eml-attachment-remover"
PROJECT_CONFIG: Final = Path(__file__).resolve().parents[2] / "pyproject.toml"


def _project_version() -> str:
    """Read the version from the source-tree project metadata.

    Returns:
        The static project version declared in ``pyproject.toml``.

    """
    with PROJECT_CONFIG.open("rb") as project_file:
        metadata = load(project_file)
    return str(metadata["project"]["version"])


def _resolved_version() -> str:
    """Read installed metadata, falling back to source-tree metadata.

    Returns:
        The version generated by packaging metadata or declared in ``pyproject.toml``.

    """
    try:
        return distribution_version(DISTRIBUTION_NAME)
    except PackageNotFoundError:
        return _project_version()


PROGRAM_VERSION: Final = _resolved_version()
