"""Public, realistic Coverage.py Cobertura XML samples for tool tests."""

from __future__ import annotations

VALID_COVERAGE_XML = b"""<?xml version="1.0" ?>
<coverage version="7.15.4" timestamp="1786680000000"
 lines-valid="2" lines-covered="1" line-rate="0.5"
 branches-valid="2" branches-covered="1" branch-rate="0.5" complexity="0">
  <!-- Generated by coverage.py: https://coverage.readthedocs.io/en/7.15.4 -->
  <!-- Based on
  https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
  <sources>
    <source>src/eml_attachment_remover</source>
    <source>tools</source>
  </sources>
  <packages>
    <package name="." line-rate="0.5" branch-rate="0.5" complexity="0">
      <classes>
        <class name="public.py" filename="public.py" complexity="0"
         line-rate="0.5" branch-rate="0.5">
          <methods/>
          <lines>
            <line number="1" hits="1" branch="true"
             condition-coverage="50% (1/2)" missing-branches="exit"/>
            <line number="2" hits="0"/>
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
"""


def altered(old: bytes, new: bytes, content: bytes = VALID_COVERAGE_XML) -> bytes:
    """Replace one uniquely occurring fragment in sample XML.

    Returns:
        The altered XML bytes.

    Raises:
        AssertionError: If the selected fragment is not unique.

    """
    if content.count(old) != 1:
        message = "Coverage XML test replacement must identify exactly one fragment"
        raise AssertionError(message)
    return content.replace(old, new)
