"""Exact staged-cleanup and public-tool receipts for remaining mutations."""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from tools import check_repository_hygiene, junit_node_id, tasks

from eml_attachment_remover import cli, staged_output
from eml_attachment_remover.domain import (
    AppError,
    BatchLedger,
    BoundDirectory,
    ExitCode,
    ItemStatus,
)
from eml_attachment_remover.native_paths import bind_destination, path_value

if TYPE_CHECKING:
    from eml_attachment_remover.staged_output import _PublicationState


def _state(tmp_path: Path) -> _PublicationState:
    """Build one direct private-stage state.

    Returns:
        A state with a real bound destination and stable candidate receipt.

    """
    candidate = b"candidate"
    return staged_output._PublicationState(  # ruff: ignore[private-member-access] - direct stage-owner receipt.
        bind_destination(str(tmp_path / "output.eml")),
        candidate,
        hashlib.sha256(candidate).hexdigest(),
    )


def test_stage_owner_transfer_rethrows_one_primary_error_without_grouping(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A clean compensating cleanup does not hide the sole stage-owner failure."""
    state = _state(tmp_path)
    state.parent = BoundDirectory(41, windows=False)
    primary = RuntimeError("owner transfer failed")
    closed: list[int] = []
    monkeypatch.setattr(staged_output, "private_stage_name", lambda: b"stage")
    monkeypatch.setattr(staged_output, "create_private_stage", lambda *_args: 51)
    monkeypatch.setattr(
        staged_output,
        "_Stage",
        lambda *_args: (_ for _ in ()).throw(primary),
    )
    monkeypatch.setattr(
        staged_output,
        "discard_private_stage",
        lambda *_args: (_ for _ in ()).throw(FileNotFoundError()),
    )
    monkeypatch.setattr(staged_output, "_close_descriptor", closed.append)

    with pytest.raises(RuntimeError) as raised:
        staged_output._create_stage(state)  # ruff: ignore[private-member-access] - owner-transfer primary cause.
    assert raised.value is primary
    assert closed == [51]


def test_stage_owner_transfer_groups_exactly_two_independent_failures(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The primary transfer and descriptor-close faults are both preserved together."""
    state = _state(tmp_path)
    state.parent = BoundDirectory(41, windows=False)
    primary = RuntimeError("owner transfer failed")
    cleanup = OSError("close failed")
    monkeypatch.setattr(staged_output, "private_stage_name", lambda: b"stage")
    monkeypatch.setattr(staged_output, "create_private_stage", lambda *_args: 51)
    monkeypatch.setattr(
        staged_output,
        "_Stage",
        lambda *_args: (_ for _ in ()).throw(primary),
    )
    monkeypatch.setattr(
        staged_output,
        "discard_private_stage",
        lambda *_args: (_ for _ in ()).throw(FileNotFoundError()),
    )
    monkeypatch.setattr(staged_output, "_close_descriptor", lambda _fd: cleanup)

    with pytest.raises(BaseExceptionGroup) as raised:
        staged_output._create_stage(state)  # ruff: ignore[private-member-access] - independent cleanup preservation.
    assert raised.value.exceptions == (primary, cleanup)


def test_cli_cancelled_status_is_independent_interruption_evidence() -> None:
    """A cancelled row means interruption even when no separate ledger record exists."""
    ledger = BatchLedger.from_requests([path_value("source.eml")])
    ledger.items[0].finish(ItemStatus.CANCELLED, AppError(ExitCode.INTERRUPTED, "stop"))
    assert cli._is_interrupted(ledger)  # ruff: ignore[private-member-access] - cancelled status receipt.


def test_generated_opaque_archive_requires_a_direct_named_artifact_root() -> None:
    """Only direct named artifact-root archives may remain opaque generated bytes."""
    build = Path("build")
    assert check_repository_hygiene._expected_opaque_archive(  # ruff: ignore[private-member-access] - direct expected archive.
        build / "remove-eml-attachments.pyz", build
    )
    assert not check_repository_hygiene._expected_opaque_archive(  # ruff: ignore[private-member-access] - nested generated byte rejection.
        build / "nested" / "remove-eml-attachments.pyz", build
    )
    assert not check_repository_hygiene._expected_opaque_archive(  # ruff: ignore[private-member-access] - absent artifact root rejection.
        Path("remove-eml-attachments.pyz"), None
    )
    other = Path("other")
    assert not check_repository_hygiene._expected_opaque_archive(  # ruff: ignore[private-member-access] - unrecognized artifact root.
        other / "remove-eml-attachments.pyz", other
    )


def test_junit_node_redaction_uses_backslashreplace_for_unpaired_surrogates(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Unsafe node IDs remain redactable when raw text is not UTF-8 encodable."""
    value = "/public/\ud800-node"
    monkeypatch.setattr(
        junit_node_id.__dict__["path_safety"],
        "contains_absolute_path",
        lambda _value: True,
    )
    expected = hashlib.sha256(value.encode("utf-8", "backslashreplace")).hexdigest()
    assert junit_node_id.redact(value) == (
        f"{junit_node_id.REDACTED_PREFIX}{expected[: junit_node_id.DIGEST_LENGTH]}"
    )


def test_task_environment_removes_absent_strict_variables_without_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Strict child environment cleanup is absence-safe before caller overrides."""
    ambient = {"KEEP": "ambient"}
    monkeypatch.setattr(os.environ, "copy", lambda: dict(ambient))
    environment = tasks._task_environment(  # ruff: ignore[private-member-access] - strict environment cleanup.
        environment_removals=("MISSING",),
        environment_updates={"KEEP": "updated"},
    )
    assert environment == {
        "KEEP": "updated",
        "PYTHONDEVMODE": "1",
        "PYTHONDONTWRITEBYTECODE": "1",
        "PYTHONNOUSERSITE": "1",
        "PYTHONWARNINGS": "error",
    }
